language: rust
rust:
  - stable
  - nightly

os:
  - linux

addons:
  apt:
    packages:
      - libnl-3-dev
      - libnl-3-200
      - libnl-genl-3-dev
      - libnl-genl-3-200

script:
  - cargo test -- --nocapture

cache: cargo

branches:
  only:
    - master

after_success: |
  cargo doc \
  && echo '<meta http-equiv=refresh content=0;url=netlink_sys/index.html>' > target/doc/index.html && \
  sudo pip install ghp-import && \
  ghp-import -n target/doc && \
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
